const { promises: fs } = require("node:fs");
const path = require("node:path");
const {
	IOSConfig,
	withAppDelegate,
	withDangerousMod,
	withInfoPlist,
	withXcodeProject,
} = require("expo/config-plugins");

const SCENE_DELEGATE_FILE = "SceneDelegate.swift";

/**
 * Moves the app onto the UIScene life cycle. An app built with the iOS 27 SDK
 * that still sets its window up in the app delegate traps in UIKit on launch
 * (`_UIApplicationEvaluateRuntimeIssueForNoSceneLifecycleAdoption`), and
 * Expo's template still does exactly that.
 *
 * Single scene only: the app delegate keeps owning the React Native factory
 * and Expo's subscribers; the scene delegate creates the window, starts React
 * Native in it, and forwards the URLs, user activities and lifecycle
 * callbacks UIKit now sends to the scene instead of the app delegate.
 *
 * @type {import("expo/config-plugins").ConfigPlugin}
 */
const withSceneLifecycle = (config) => {
	config = withInfoPlist(config, (config) => {
		config.modResults.UIApplicationSceneManifest = {
			UIApplicationSupportsMultipleScenes: false,
			UISceneConfigurations: {
				UIWindowSceneSessionRoleApplication: [
					{
						UISceneConfigurationName: "Default Configuration",
						UISceneDelegateClassName: "$(PRODUCT_MODULE_NAME).SceneDelegate",
					},
				],
			},
		};
		return config;
	});

	config = withAppDelegate(config, (config) => {
		if (config.modResults.language !== "swift") {
			throw new Error("withSceneLifecycle: expected a Swift AppDelegate");
		}
		config.modResults.contents = rewriteAppDelegate(config.modResults.contents);
		return config;
	});

	config = withDangerousMod(config, [
		"ios",
		async (config) => {
			await fs.writeFile(
				path.join(
					config.modRequest.platformProjectRoot,
					config.modRequest.projectName ?? "Superset",
					SCENE_DELEGATE_FILE,
				),
				SCENE_DELEGATE,
			);
			return config;
		},
	]);

	return withXcodeProject(config, (config) => {
		const projectName = config.modRequest.projectName ?? "Superset";
		const filepath = `${projectName}/${SCENE_DELEGATE_FILE}`;
		if (!config.modResults.hasFile(filepath)) {
			IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
				filepath,
				groupName: projectName,
				project: config.modResults,
			});
		}
		return config;
	});
};

/**
 * The template starts React Native in a window it makes itself; under scenes
 * that window has no scene and never shows. Keep the launch options for the
 * scene delegate instead, which starts React Native once it has a scene.
 */
function rewriteAppDelegate(contents) {
	if (contents.includes("var launchOptions:")) return contents;

	const windowSetup =
		/#if os\(iOS\) \|\| os\(tvOS\)\n\s*window = UIWindow\(frame: UIScreen\.main\.bounds\)\n\s*factory\.startReactNative\(\n\s*withModuleName: "main",\n\s*in: window,\n\s*launchOptions: launchOptions\)\n#endif\n/;
	const property = "  var reactNativeFactory: RCTReactNativeFactory?\n";
	if (!windowSetup.test(contents) || !contents.includes(property)) {
		throw new Error(
			"withSceneLifecycle: AppDelegate.swift no longer matches the Expo template; update the plugin",
		);
	}

	return contents
		.replace(
			property,
			`${property}  /// Read by SceneDelegate, which starts React Native once a scene exists.\n  var launchOptions: [UIApplication.LaunchOptionsKey: Any]?\n`,
		)
		.replace(windowSetup, "    self.launchOptions = launchOptions\n\n");
}

const SCENE_DELEGATE = `import React
import UIKit

/// Generated by config-plugins/withSceneLifecycle.js — edit it there.
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  private var appDelegate: AppDelegate? {
    UIApplication.shared.delegate as? AppDelegate
  }

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene,
      let appDelegate,
      let factory = appDelegate.reactNativeFactory
    else { return }

    let window = UIWindow(windowScene: windowScene)
    self.window = window
    appDelegate.window = window
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions(
        base: appDelegate.launchOptions,
        connectionOptions: connectionOptions))
  }

  /// A cold launch's URL or universal link arrives on the scene, not in the
  /// app's launch options; put it back where Linking.getInitialURL and the
  /// dev launcher look for it.
  private func launchOptions(
    base: [UIApplication.LaunchOptionsKey: Any]?,
    connectionOptions: UIScene.ConnectionOptions
  ) -> [UIApplication.LaunchOptionsKey: Any] {
    var options = base ?? [:]
    if let url = connectionOptions.urlContexts.first?.url {
      options[.url] = url
    }
    if let activity = connectionOptions.userActivities.first {
      options[.userActivityDictionary] = [
        UIApplication.LaunchOptionsKey.userActivityType.rawValue: activity.activityType,
        "UIApplicationLaunchOptionsUserActivityKey": activity,
      ]
    }
    return options
  }

  // MARK: - Forwarded to the app delegate, where Expo's subscribers and
  // RCTLinkingManager listen; UIKit no longer calls these there.

  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    for context in URLContexts {
      var options: [UIApplication.OpenURLOptionsKey: Any] = [
        .openInPlace: context.options.openInPlace
      ]
      if let source = context.options.sourceApplication {
        options[.sourceApplication] = source
      }
      if let annotation = context.options.annotation {
        options[.annotation] = annotation
      }
      _ = appDelegate?.application(.shared, open: context.url, options: options)
    }
  }

  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    _ = appDelegate?.application(
      .shared, continue: userActivity, restorationHandler: { _ in })
  }

  func sceneDidBecomeActive(_ scene: UIScene) {
    appDelegate?.applicationDidBecomeActive(.shared)
  }

  func sceneWillResignActive(_ scene: UIScene) {
    appDelegate?.applicationWillResignActive(.shared)
  }

  func sceneWillEnterForeground(_ scene: UIScene) {
    appDelegate?.applicationWillEnterForeground(.shared)
  }

  func sceneDidEnterBackground(_ scene: UIScene) {
    appDelegate?.applicationDidEnterBackground(.shared)
  }
}
`;

module.exports = { rewriteAppDelegate, SCENE_DELEGATE, withSceneLifecycle };
