# Optional building on https://reporoad.org
# After merging, submit this repository at https://reporoad.org to join.
version: 1
style: greenhouse
color: "#778565"
roof: gable
signText: Superset
garden: true
support:
  sponsor: false
  helpWanted: false
