/**
 * Build script that bundles the annotation injection wrapper into a self-contained
 * IIFE string. This is meant to be run at build time (or imported at runtime
 * by the main process) to produce the JS that gets injected into webviews.
 *
 * Usage:
 *   bun run apps/desktop/src/main/lib/browser/annotation/build-bundle.ts
 *
 * The resulting bundle includes React, ReactDOM, and the agentation package
 * in a single IIFE that auto-mounts when evaluated.
 */

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const __dirname = dirname(fileURLToPath(import.meta.url));

async function buildBundle() {
	const entryPoint = resolve(__dirname, "injection-wrapper.ts");
	const outfile = resolve(__dirname, "annotation-bundle.js");

	const result = await build({
		entryPoints: [entryPoint],
		bundle: true,
		format: "iife",
		globalName: "__supersetAnnotationBundle",
		platform: "browser",
		target: ["chrome120"],
		minify: true,
		write: false,
		// React is bundled in (not external) since the webview page may not have React
		define: {
			"process.env.NODE_ENV": '"production"',
		},
		jsx: "automatic",
		loader: {
			".tsx": "tsx",
			".ts": "ts",
			".scss": "css",
		},
	});

	const code = result.outputFiles[0].text;
	// Write the bundle as a TypeScript module that exports the code as a string constant
	const moduleContent = `// Auto-generated by build-bundle.ts — do not edit manually\nexport const ANNOTATION_BUNDLE = ${JSON.stringify(code)};\n`;
	writeFileSync(outfile, code);

	// Also write as a TS module for direct import
	const tsModulePath = resolve(__dirname, "annotation-bundle-string.ts");
	writeFileSync(tsModulePath, moduleContent);

	console.log(
		`Annotation bundle built: ${(code.length / 1024).toFixed(1)}KB (raw)`,
	);
}

buildBundle().catch((err) => {
	console.error("Failed to build annotation bundle:", err);
	process.exit(1);
});
