import type { GitFile } from "./types";

export const mockGitFiles: GitFile[] = [
	{
		id: "1",
		path: "src/components/Button.tsx",
		name: "Button.tsx",
		status: "modified",
		staged: true,
	},
	{
		id: "2",
		path: "src/components/Input.tsx",
		name: "Input.tsx",
		status: "added",
		staged: false,
	},
	{
		id: "3",
		path: "src/utils/helpers.ts",
		name: "helpers.ts",
		status: "modified",
		staged: true,
	},
	{
		id: "4",
		path: "src/utils/format.ts",
		name: "format.ts",
		status: "deleted",
		staged: false,
	},
	{
		id: "5",
		path: "src/hooks/useAuth.ts",
		name: "useAuth.ts",
		status: "modified",
		staged: false,
	},
	{
		id: "6",
		path: "src/hooks/useTheme.ts",
		name: "useTheme.ts",
		status: "added",
		staged: true,
	},
	{
		id: "7",
		path: "src/lib/api.ts",
		name: "api.ts",
		status: "modified",
		staged: true,
	},
	{
		id: "8",
		path: "src/lib/db.ts",
		name: "db.ts",
		status: "renamed",
		oldPath: "src/lib/database.ts",
		staged: true,
	},
	{
		id: "9",
		path: "tests/components/Button.test.tsx",
		name: "Button.test.tsx",
		status: "added",
		staged: false,
	},
	{
		id: "10",
		path: "tests/utils/helpers.test.ts",
		name: "helpers.test.ts",
		status: "modified",
		staged: false,
	},
	{
		id: "11",
		path: "package.json",
		name: "package.json",
		status: "modified",
		staged: true,
	},
	{
		id: "12",
		path: "tsconfig.json",
		name: "tsconfig.json",
		status: "modified",
		staged: false,
	},
	{
		id: "13",
		path: "README.md",
		name: "README.md",
		status: "modified",
		staged: true,
	},
	{
		id: "14",
		path: "src/styles/globals.css",
		name: "globals.css",
		status: "modified",
		staged: false,
	},
	{
		id: "15",
		path: "src/app/layout.tsx",
		name: "layout.tsx",
		status: "added",
		staged: true,
	},
	{
		id: "16",
		path: "src/app/page.tsx",
		name: "page.tsx",
		status: "modified",
		staged: false,
	},
	{
		id: "17",
		path: "public/favicon.ico",
		name: "favicon.ico",
		status: "untracked",
		staged: false,
	},
	{
		id: "18",
		path: "docs/getting-started.md",
		name: "getting-started.md",
		status: "added",
		staged: false,
	},
];
