import { toast } from "@superset/ui/sonner";
import { useNavigate } from "@tanstack/react-router";
import { useCallback } from "react";
import { authClient } from "renderer/lib/auth-client";
import { useLocalHostService } from "renderer/routes/_authenticated/providers/LocalHostServiceProvider";
import { useWorkspaceCreates } from "renderer/stores/workspace-creates";
import { useDashboardNewWorkspaceDraft } from "../../../../../DashboardNewWorkspaceDraftContext";
import type { WorkspaceCreateAgent } from "../../types";
import type { UseUploadAttachmentsApi } from "../useUploadAttachments";
import { resolveNames } from "./resolveNames";

/**
 * Submits a workspace create against the new `workspaces.create` host
 * procedure. Attachment uploads run optimistically through `useUploadAttachments`
 * — submit only blocks on whatever uploads are still in flight, then dispatches
 * the create with the resulting `attachmentIds` on the agent launch sugar.
 */
export function useSubmitWorkspace(
	projectId: string | null,
	selectedAgent: WorkspaceCreateAgent,
	uploadAttachments: UseUploadAttachmentsApi,
) {
	const navigate = useNavigate();
	const { closeAndResetDraft, draft } = useDashboardNewWorkspaceDraft();
	const { submit } = useWorkspaceCreates();
	const { machineId } = useLocalHostService();
	const { data: session } = authClient.useSession();
	const activeOrganizationId = session?.session?.activeOrganizationId;

	return useCallback(async () => {
		if (!projectId) {
			toast.error("Select a project first");
			return;
		}
		if (!activeOrganizationId) {
			toast.error("No active organization");
			return;
		}

		const hostId = draft.hostId ?? machineId;
		if (!hostId) {
			toast.error("No active host");
			return;
		}

		const { readyIds: attachmentIds, errors } =
			await uploadAttachments.awaitUploads();
		if (errors.length > 0) {
			const first = errors[0];
			toast.error(
				first.filename
					? `Attachment upload failed (${first.filename}): ${first.message}`
					: `Attachment upload failed: ${first.message}`,
			);
			return;
		}

		const { branchName, workspaceName, workspaceNameWasAutoGenerated } =
			resolveNames(draft);

		const isPrCheckout = draft.linkedPR !== null;

		const taskIds = draft.linkedIssues
			.filter((issue) => issue.source === "internal" && issue.taskId)
			.map((issue) => issue.taskId as string);

		const agents =
			selectedAgent !== "none" && draft.prompt.trim()
				? [
						{
							agent: selectedAgent,
							prompt: draft.prompt,
							attachmentIds:
								attachmentIds.length > 0 ? attachmentIds : undefined,
						},
					]
				: undefined;

		const displayName = isPrCheckout
			? draft.linkedPR?.title || `PR #${draft.linkedPR?.prNumber}`
			: workspaceName;

		const workspaceId = crypto.randomUUID();
		const snapshot = {
			id: workspaceId,
			projectId,
			name: isPrCheckout ? displayName : workspaceName,
			branch: isPrCheckout ? undefined : branchName,
			pr: isPrCheckout ? draft.linkedPR?.prNumber : undefined,
			baseBranch: draft.baseBranch ?? undefined,
			taskIds: taskIds.length > 0 ? taskIds : undefined,
			autogenerateName:
				!isPrCheckout &&
				workspaceNameWasAutoGenerated &&
				Boolean(draft.prompt.trim()),
			agents,
		};

		closeAndResetDraft();
		void navigate({ to: `/v2-workspace/${workspaceId}` as string });
		void submit({ hostId, snapshot });
	}, [
		activeOrganizationId,
		closeAndResetDraft,
		draft,
		machineId,
		navigate,
		projectId,
		selectedAgent,
		submit,
		uploadAttachments,
	]);
}
