// Entry point used by app/_layout.tsx when EXPO_PUBLIC_STORYBOOK=true.
// `storybook.requires` is generated by `sb-rn-get-stories` at dev-time —
// see the "storybook" script in package.json. It is gitignored.
import { view } from "./storybook.requires";

const StorybookUIRoot = view.getStorybookUI({
	shouldPersistSelection: true,
});

export default StorybookUIRoot;
