// Entry point used by app/_layout.tsx when EXPO_PUBLIC_STORYBOOK=true.
// `storybook.requires` is generated by `sb-rn-get-stories` at dev-time —
// see the "storybook" script in package.json. It is gitignored.
import AsyncStorage from "@react-native-async-storage/async-storage";
import { StorybookRouterProvider } from "./StorybookRouterProvider";
import { view } from "./storybook.requires";

// Storybook v9 react-native requires the `storage` adapter to be passed
// explicitly when `shouldPersistSelection: true` — it does not auto-detect
// AsyncStorage. Without this, attempts to read the persisted story selection
// throw `TypeError: Cannot read property 'getItem' of undefined`.
const StorybookUIRoot = view.getStorybookUI({
	shouldPersistSelection: true,
	storage: {
		getItem: AsyncStorage.getItem,
		setItem: AsyncStorage.setItem,
	},
});

export default function StorybookRoot() {
	return (
		<StorybookRouterProvider>
			<StorybookUIRoot />
		</StorybookRouterProvider>
	);
}
