export {
	applyFolderTagChange,
	buildSidebarFolderKey,
	DERIVED_TAG_FOLDER_TAB_ORDER_BASE,
	deriveTagFolders,
	getProjectFolderTagIndex,
	mintFolderTag,
	parseSidebarFolderKey,
	resolveWorkspaceFolder,
	resolveWorkspaceSectionId,
	type TagFolderRef,
	type TagFolderSection,
	type TagFolderSectionInput,
	type TagFolderWorkspaceInput,
} from "./workspaceTagFolders";
