import type { UITask } from "./types";

// Mock tasks data - TODO: Replace with actual task data from backend
export const MOCK_TASKS: UITask[] = [
    {
        id: "1",
        slug: "SSET-1",
        name: "Homepage Redesign",
        status: "working",
        branch: "feature/homepage-redesign",
        description: "Redesigning the homepage with new branding and improved UX",
        assignee: "Alice",
        assigneeAvatarUrl: "https://i.pravatar.cc/150?img=1",
        lastUpdated: "2 hours ago",
    },
    {
        id: "2",
        slug: "SSET-2",
        name: "API Integration",
        status: "needs-feedback",
        branch: "feature/api-integration",
        description: "Integrate new REST API endpoints for user management",
        assignee: "Bob",
        assigneeAvatarUrl: "https://i.pravatar.cc/150?img=12",
        lastUpdated: "1 day ago",
    },
    {
        id: "3",
        slug: "SSET-3",
        name: "Bug Fixes",
        status: "planning",
        branch: "fix/various-bugs",
        description: "Collection of bug fixes reported by users",
        assignee: "Charlie",
        assigneeAvatarUrl: "https://i.pravatar.cc/150?img=33",
        lastUpdated: "3 days ago",
    },
    {
        id: "4",
        slug: "SSET-4",
        name: "Performance Optimization",
        status: "ready-to-merge",
        branch: "perf/optimize-queries",
        description: "Optimize database queries for faster page loads",
        assignee: "Diana",
        assigneeAvatarUrl: "https://i.pravatar.cc/150?img=9",
        lastUpdated: "5 minutes ago",
    },
    {
        id: "5",
        slug: "SSET-5",
        name: "User Authentication System",
        status: "working",
        branch: "feature/auth-system",
        description:
            "Implement OAuth2 and JWT-based authentication system with refresh tokens",
        assignee: "Eve",
        assigneeAvatarUrl: "https://i.pravatar.cc/150?img=5",
        lastUpdated: "3 hours ago",
    },
    {
        id: "6",
        slug: "SSET-6",
        name: "Dark Mode Support",
        status: "planning",
        branch: "feature/dark-mode",
        description: "Add dark mode theme support across the entire application",
        assignee: "Frank",
        assigneeAvatarUrl: "https://i.pravatar.cc/150?img=13",
        lastUpdated: "2 days ago",
    },
    {
        id: "7",
        slug: "SSET-7",
        name: "Database Migration Scripts",
        status: "ready-to-merge",
        branch: "db/migration-scripts",
        description:
            "Create automated migration scripts for production database updates",
        assignee: "Grace",
        assigneeAvatarUrl: "https://i.pravatar.cc/150?img=20",
        lastUpdated: "1 hour ago",
    },
    {
        id: "8",
        slug: "SSET-8",
        name: "Email Notification Service",
        status: "needs-feedback",
        branch: "feature/email-notifications",
        description:
            "Build email notification service using SendGrid for transactional emails",
        assignee: "Henry",
        assigneeAvatarUrl: "https://i.pravatar.cc/150?img=8",
        lastUpdated: "4 hours ago",
    },
    {
        id: "9",
        slug: "SSET-9",
        name: "Mobile Responsive Design",
        status: "working",
        branch: "feature/mobile-responsive",
        description:
            "Make the application fully responsive for mobile and tablet devices",
        assignee: "Iris",
        assigneeAvatarUrl: "https://i.pravatar.cc/150?img=16",
        lastUpdated: "6 hours ago",
    },
    {
        id: "10",
        slug: "SSET-10",
        name: "Analytics Dashboard",
        status: "planning",
        branch: "feature/analytics-dashboard",
        description:
            "Create admin dashboard with charts and metrics for user analytics",
        assignee: "Jack",
        assigneeAvatarUrl: "https://i.pravatar.cc/150?img=11",
        lastUpdated: "1 week ago",
    },
    {
        id: "11",
        slug: "SSET-11",
        name: "CI/CD Pipeline",
        status: "ready-to-merge",
        branch: "devops/ci-cd-pipeline",
        description:
            "Set up automated CI/CD pipeline with GitHub Actions and Docker",
        assignee: "Kate",
        assigneeAvatarUrl: "https://i.pravatar.cc/150?img=25",
        lastUpdated: "30 minutes ago",
    },
    {
        id: "12",
        slug: "SSET-12",
        name: "Search Functionality",
        status: "working",
        branch: "feature/search",
        description: "Implement full-text search with Elasticsearch integration",
        assignee: "Liam",
        assigneeAvatarUrl: "https://i.pravatar.cc/150?img=14",
        lastUpdated: "5 hours ago",
    },
    {
        id: "13",
        slug: "SSET-13",
        name: "File Upload System",
        status: "needs-feedback",
        branch: "feature/file-uploads",
        description:
            "Build secure file upload system with S3 storage and virus scanning",
        assignee: "Mia",
        assigneeAvatarUrl: "https://i.pravatar.cc/150?img=27",
        lastUpdated: "2 hours ago",
    },
    {
        id: "14",
        slug: "SSET-14",
        name: "API Rate Limiting",
        status: "planning",
        branch: "feature/rate-limiting",
        description: "Implement rate limiting and throttling for API endpoints",
        assignee: "Noah",
        assigneeAvatarUrl: "https://i.pravatar.cc/150?img=17",
        lastUpdated: "4 days ago",
    },
    {
        id: "15",
        slug: "SSET-15",
        name: "Internationalization",
        status: "working",
        branch: "feature/i18n",
        description:
            "Add multi-language support with i18next for English, Spanish, and French",
        assignee: "Olivia",
        assigneeAvatarUrl: "https://i.pravatar.cc/150?img=32",
        lastUpdated: "8 hours ago",
    },
];

