/**
 * 에러 코드 네이밍 규칙: {DOMAIN}_{CATEGORY}_{SPECIFIC}
 * - DOMAIN: 도메인 (AUTH, USER, BLOG, PAYMENT 등)
 * - CATEGORY: 카테고리 (VALIDATION, NOT_FOUND, FORBIDDEN 등)
 * - SPECIFIC: 구체적 상황 (선택)
 */
export const ErrorCode = {
  // ========== Common (공통) ==========
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  RATE_LIMITED: "RATE_LIMITED",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  // ========== Auth (인증) ==========
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
  AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_USER_DISABLED: "AUTH_USER_DISABLED",
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_WEAK_PASSWORD: "AUTH_WEAK_PASSWORD",

  // ========== User (사용자) ==========
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_PROFILE_INCOMPLETE: "USER_PROFILE_INCOMPLETE",

  // ========== Resource (리소스) ==========
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",

  // ========== Permission (권한) ==========
  PERMISSION_DENIED: "PERMISSION_DENIED",
  ADMIN_REQUIRED: "ADMIN_REQUIRED",
  OWNER_REQUIRED: "OWNER_REQUIRED",

  // ========== Community (커뮤니티) ==========
  COMMUNITY_NOT_FOUND: "COMMUNITY_NOT_FOUND",
  ALREADY_MEMBER: "ALREADY_MEMBER",
  NOT_MEMBER: "NOT_MEMBER",
  DUPLICATE_VOTE: "DUPLICATE_VOTE",

  // ========== External Service (외부 서비스) ==========
  EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
