#!/usr/bin/env bun
/**
 * Local dev launcher. The port and the secret come from the worktree's .env —
 * the secret must be the one the API signs with — folded into a generated
 * .dev.vars.dev that wrangler reads for --env dev.
 */
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const appDir = join(import.meta.dir, "..");
const repoRoot = join(appDir, "..", "..");

function parseEnvFile(path: string): Record<string, string> {
	if (!existsSync(path)) return {};
	const out: Record<string, string> = {};
	for (const line of readFileSync(path, "utf8").split("\n")) {
		const match = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*"?([^"\n]*)"?\s*$/.exec(
			line,
		);
		if (match) out[match[1] as string] = (match[2] as string).trim();
	}
	return out;
}

const rootEnv = parseEnvFile(join(repoRoot, ".env"));
const port = Number(
	process.env.SANDBOX_EDGE_DEV_PORT ?? rootEnv.SANDBOX_EDGE_DEV_PORT ?? 8790,
);
const secret = process.env.SANDBOX_EDGE_SECRET ?? rootEnv.SANDBOX_EDGE_SECRET;
if (!secret) {
	console.error("[sandbox-edge] SANDBOX_EDGE_SECRET is not set in .env");
	process.exit(1);
}

writeFileSync(
	join(appDir, ".dev.vars.dev"),
	[
		"# Generated by scripts/dev.ts from the worktree's .env — do not edit.",
		`SANDBOX_EDGE_SECRET=${secret}`,
		"",
	].join("\n"),
);
console.log(`[sandbox-edge] wrangler dev on :${port}`);
const result = spawnSync(
	"bunx",
	["wrangler", "dev", "--env", "dev", "--port", String(port)],
	{ stdio: "inherit", cwd: appDir },
);
process.exit(result.status ?? 0);
