import { existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { getDeviceName, getHashedDeviceId } from "@superset/shared/device-info";
import { TRPCError } from "@trpc/server";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { projects, workspaces } from "../../../../db/schema";
import {
	asRemoteRef,
	type ResolvedRef,
	resolveDefaultBranchName,
	resolveUpstream,
} from "../../../../runtime/git/refs";
import { createTerminalSessionInternal } from "../../../../terminal/terminal";
import { protectedProcedure } from "../../../index";
import { buildStartPointFromHint, listBranchNames } from "../branch-helpers";
import { projectNotSetupError, safeResolveWorktreePath } from "../helpers";
import { clearProgress, setProgress } from "../progress";
import { generateWorkspaceNameFromPrompt } from "../utils/ai-workspace-name";
import { resolveStartPoint } from "../utils/resolve-start-point";
import { deduplicateBranchName } from "../utils/sanitize-branch";

/**
 * Create a new workspace. Always creates — never opens an existing one.
 * Branch name is sanitized and deduplicated server-side.
 */
export const create = protectedProcedure
	.input(
		z.object({
			pendingId: z.string(),
			projectId: z.string(),
			names: z.object({
				workspaceName: z.string(),
				branchName: z.string(),
				// Renderer signal: true when `workspaceName` came from the
				// friendly-random fallback (no user-typed title). Gates the
				// post-create AI rename so a user-typed title is never
				// overwritten. Optional for backcompat — defaults to allowing
				// the rename, matching pre-field behavior.
				workspaceNameWasAutoGenerated: z.boolean().optional(),
			}),
			composer: z.object({
				prompt: z.string().optional(),
				baseBranch: z.string().optional(),
				// Hint from the picker about which form of the base branch
				// was selected. When provided, the server uses it directly
				// instead of probing — avoids racing against stale cached
				// remote refs that could win in a re-resolve. See
				// `resolve-start-point.ts` for the fallback semantics.
				baseBranchSource: z.enum(["local", "remote-tracking"]).optional(),
				runSetupScript: z.boolean().optional(),
			}),
			linkedContext: z
				.object({
					internalIssueIds: z.array(z.string()).optional(),
					githubIssueUrls: z.array(z.string()).optional(),
					linkedPrUrl: z.string().optional(),
					attachments: z
						.array(
							z.object({
								data: z.string(),
								mediaType: z.string(),
								filename: z.string().optional(),
							}),
						)
						.optional(),
				})
				.optional(),
		}),
	)
	.mutation(async ({ ctx, input }) => {
		const deviceClientId = getHashedDeviceId();
		const deviceName = getDeviceName();
		setProgress(input.pendingId, "ensuring_repo");

		const localProject = ctx.db.query.projects
			.findFirst({ where: eq(projects.id, input.projectId) })
			.sync();
		if (!localProject) {
			throw projectNotSetupError(input.projectId);
		}

		setProgress(input.pendingId, "creating_worktree");

		// 2. Validate + deduplicate branch name
		// Renderer already sanitized/slugified. Host-service only validates
		// and deduplicates — doesn't re-sanitize (which would strip case,
		// slashes, etc. the user intended).
		if (!input.names.branchName.trim()) {
			throw new TRPCError({
				code: "BAD_REQUEST",
				message: "Branch name is empty",
			});
		}

		const existingBranches = await listBranchNames(ctx, localProject.repoPath);
		const branchName = deduplicateBranchName(
			input.names.branchName,
			existingBranches,
		);

		// 3. Create worktree
		const worktreePath = safeResolveWorktreePath(localProject.id, branchName);
		mkdirSync(dirname(worktreePath), { recursive: true });

		const git = await ctx.git(localProject.repoPath);

		// Trust the picker's hint when provided: it knows whether the row
		// the user clicked was local or remote-only. Re-resolving here
		// races against stale cached refs (a workspace branch with an
		// incidental `refs/remotes/origin/<name>` cache would silently win).
		// Falls back to probing for callers that don't pass the hint.
		let startPoint: ResolvedRef =
			input.composer.baseBranch && input.composer.baseBranchSource
				? buildStartPointFromHint(
						input.composer.baseBranch,
						input.composer.baseBranchSource,
					)
				: await resolveStartPoint(git, input.composer.baseBranch);

		// Local default branches are rarely fast-forwarded; swap to the
		// branch's configured upstream so we fork from the real tip, not a
		// stale local ref. Non-default branches stay local-first by design.
		if (startPoint.kind === "local") {
			const defaultBranchName = await resolveDefaultBranchName(git);
			if (startPoint.shortName === defaultBranchName) {
				const upstream = await resolveUpstream(git, defaultBranchName);
				if (upstream) {
					const remoteRef = asRemoteRef(upstream.remote, upstream.remoteBranch);
					const remoteExists = await git
						.raw(["rev-parse", "--verify", "--quiet", `${remoteRef}^{commit}`])
						.then(() => true)
						.catch(() => false);
					if (remoteExists) {
						startPoint = {
							kind: "remote-tracking",
							fullRef: remoteRef,
							shortName: upstream.remoteBranch,
							remote: upstream.remote,
							remoteShortName: `${upstream.remote}/${upstream.remoteBranch}`,
						};
					}
				}
			}
		}

		console.log(
			`[workspaceCreation.create] start point: ${startPoint.kind} (${
				input.composer.baseBranchSource ? "from hint" : "resolved"
			})`,
		);

		// If we resolved to a remote-tracking ref, fetch just that branch
		// to ensure we're branching from the latest remote state.
		if (startPoint.kind === "remote-tracking") {
			try {
				await git.fetch([
					startPoint.remote,
					startPoint.shortName,
					"--quiet",
					"--no-tags",
				]);
			} catch (err) {
				console.warn(
					`[workspaceCreation.create] fetch ${startPoint.remoteShortName} failed, proceeding with local ref:`,
					err,
				);
			}
		}

		// Always create a new branch — never check out an existing one.
		// Checking out existing branches is a separate intent (createFromPr,
		// or the picker's Check out action via the `checkout` procedure).
		// --no-track keeps `git pull` / ahead-behind counts from treating
		// the start point as the branch's home. Push targeting is handled
		// separately by push.autoSetupRemote (set below).
		const startPointArg =
			startPoint.kind === "head" ? "HEAD" : startPoint.shortName;
		await git.raw([
			"worktree",
			"add",
			"--no-track",
			"-b",
			branchName,
			worktreePath,
			startPoint.kind === "remote-tracking"
				? startPoint.remoteShortName
				: startPointArg,
		]);

		// Enable autoSetupRemote so the first terminal `git push` creates
		// origin/<branchName> and sets it as upstream without requiring
		// `-u`. Note: `--local` in a linked worktree writes to the shared
		// repo config, so this applies repo-wide — intentional, every
		// workspace worktree wants the same ergonomics. Safe against
		// wrong-upstream targeting because --no-track above guarantees no
		// upstream exists at first push, so auto-create always wins and
		// always uses the branch's own name (never the base branch).
		await git
			.raw([
				"-C",
				worktreePath,
				"config",
				"--local",
				"push.autoSetupRemote",
				"true",
			])
			.catch((err) => {
				console.warn(
					"[workspaceCreation.create] failed to set push.autoSetupRemote:",
					err,
				);
			});

		// Record the base branch in git config so the Changes tab knows what
		// to compare against on first open. startPoint.shortName is the ref
		// we actually forked from (user selection, resolved against local /
		// remote). Skipped for "head" start point — no meaningful base.
		if (startPoint.kind !== "head") {
			await git
				.raw(["config", `branch.${branchName}.base`, startPoint.shortName])
				.catch((err) => {
					console.warn(
						`[workspaceCreation.create] failed to record base branch ${startPoint.shortName}:`,
						err,
					);
				});
		}

		setProgress(input.pendingId, "registering");

		// 4. Register cloud workspace row
		const rollbackWorktree = async () => {
			try {
				await git.raw(["worktree", "remove", worktreePath]);
			} catch (err) {
				console.warn("[workspaceCreation.create] failed to rollback worktree", {
					worktreePath,
					err,
				});
			}
		};

		let host: { id: string };
		try {
			host = await ctx.api.device.ensureV2Host.mutate({
				organizationId: ctx.organizationId,
				machineId: deviceClientId,
				name: deviceName,
			});
		} catch (err) {
			console.error("[workspaceCreation.create] ensureV2Host failed", err);
			clearProgress(input.pendingId);
			await rollbackWorktree();
			throw new TRPCError({
				code: "INTERNAL_SERVER_ERROR",
				message: `Failed to register host: ${err instanceof Error ? err.message : String(err)}`,
			});
		}

		const cloudRow = await ctx.api.v2Workspace.create
			.mutate({
				organizationId: ctx.organizationId,
				projectId: input.projectId,
				name: input.names.workspaceName,
				branch: branchName,
				hostId: host.id,
			})
			.catch(async (err) => {
				console.error(
					"[workspaceCreation.create] v2Workspace.create failed",
					err,
				);
				clearProgress(input.pendingId);
				await rollbackWorktree();
				throw err;
			});

		if (!cloudRow) {
			clearProgress(input.pendingId);
			await rollbackWorktree();
			throw new TRPCError({
				code: "INTERNAL_SERVER_ERROR",
				message: "Cloud workspace create returned no row",
			});
		}

		ctx.db
			.insert(workspaces)
			.values({
				id: cloudRow.id,
				projectId: input.projectId,
				worktreePath,
				branch: branchName,
			})
			.run();

		// Fire-and-forget AI rename from the composer prompt. Electric syncs
		// the new name to the renderer via v2_workspaces, so the pending/
		// workspace page will update in place once the model responds.
		//
		// Name precedence (matches renderer `resolveNames`):
		//   1. user-typed title → skip AI rename (flag = false)
		//   2. friendly fallback + prompt → AI rename (this branch)
		//   3. friendly fallback, no prompt → keep fallback
		//
		// `expectedCurrentName` covers the race where a user edits the
		// title after create but before the AI response lands.
		const composerPrompt = input.composer.prompt?.trim();
		const allowAiRename = input.names.workspaceNameWasAutoGenerated !== false;
		if (composerPrompt && allowAiRename) {
			void generateWorkspaceNameFromPrompt(composerPrompt)
				.then(async (aiName) => {
					if (!aiName || aiName === input.names.workspaceName) return;
					await ctx.api.v2Workspace.updateNameFromHost.mutate({
						id: cloudRow.id,
						name: aiName,
						expectedCurrentName: input.names.workspaceName,
					});
				})
				.catch((err) => {
					console.warn(
						"[workspaceCreation.create] AI workspace rename failed",
						err,
					);
				});
		}

		// 5. Create setup terminal if setup script exists
		const terminals: Array<{
			id: string;
			role: string;
			label: string;
		}> = [];
		const warnings: string[] = [];

		if (input.composer.runSetupScript) {
			const setupScriptPath = join(worktreePath, ".superset", "setup.sh");
			if (existsSync(setupScriptPath)) {
				const terminalId = crypto.randomUUID();
				const result = createTerminalSessionInternal({
					terminalId,
					workspaceId: cloudRow.id,
					db: ctx.db,
					initialCommand: `bash "${setupScriptPath}"`,
				});
				if ("error" in result) {
					warnings.push(`Failed to start setup terminal: ${result.error}`);
				} else {
					terminals.push({
						id: terminalId,
						role: "setup",
						label: "Workspace Setup",
					});
				}
			}
		}

		clearProgress(input.pendingId);

		return {
			workspace: cloudRow,
			terminals,
			warnings,
		};
	});
