/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/layout'
import { Route as PageRouteImport } from './routes/page'
import { Route as SignInPageRouteImport } from './routes/sign-in/page'
import { Route as CreateOrganizationPageRouteImport } from './routes/create-organization/page'
import { Route as AuthenticatedSettingsLayoutRouteImport } from './routes/_authenticated/settings/layout'
import { Route as AuthenticatedOnboardingLayoutRouteImport } from './routes/_authenticated/_onboarding/layout'
import { Route as AuthenticatedDashboardLayoutRouteImport } from './routes/_authenticated/_dashboard/layout'
import { Route as AuthenticatedSettingsPageRouteImport } from './routes/_authenticated/settings/page'
import { Route as AuthenticatedDashboardV2WorkspaceLayoutRouteImport } from './routes/_authenticated/_dashboard/v2-workspace/layout'
import { Route as AuthenticatedDashboardTasksLayoutRouteImport } from './routes/_authenticated/_dashboard/tasks/layout'
import { Route as AuthenticatedSettingsTerminalPageRouteImport } from './routes/_authenticated/settings/terminal/page'
import { Route as AuthenticatedSettingsSecurityPageRouteImport } from './routes/_authenticated/settings/security/page'
import { Route as AuthenticatedSettingsRingtonesPageRouteImport } from './routes/_authenticated/settings/ringtones/page'
import { Route as AuthenticatedSettingsProjectsPageRouteImport } from './routes/_authenticated/settings/projects/page'
import { Route as AuthenticatedSettingsPresetsPageRouteImport } from './routes/_authenticated/settings/presets/page'
import { Route as AuthenticatedSettingsPermissionsPageRouteImport } from './routes/_authenticated/settings/permissions/page'
import { Route as AuthenticatedSettingsOrganizationPageRouteImport } from './routes/_authenticated/settings/organization/page'
import { Route as AuthenticatedSettingsModelsPageRouteImport } from './routes/_authenticated/settings/models/page'
import { Route as AuthenticatedSettingsKeyboardPageRouteImport } from './routes/_authenticated/settings/keyboard/page'
import { Route as AuthenticatedSettingsIntegrationsPageRouteImport } from './routes/_authenticated/settings/integrations/page'
import { Route as AuthenticatedSettingsGitPageRouteImport } from './routes/_authenticated/settings/git/page'
import { Route as AuthenticatedSettingsBillingPageRouteImport } from './routes/_authenticated/settings/billing/page'
import { Route as AuthenticatedSettingsBehaviorPageRouteImport } from './routes/_authenticated/settings/behavior/page'
import { Route as AuthenticatedSettingsAppearancePageRouteImport } from './routes/_authenticated/settings/appearance/page'
import { Route as AuthenticatedSettingsApiKeysPageRouteImport } from './routes/_authenticated/settings/api-keys/page'
import { Route as AuthenticatedSettingsAgentsPageRouteImport } from './routes/_authenticated/settings/agents/page'
import { Route as AuthenticatedSettingsAccountPageRouteImport } from './routes/_authenticated/settings/account/page'
import { Route as AuthenticatedOnboardingWelcomePageRouteImport } from './routes/_authenticated/_onboarding/welcome/page'
import { Route as AuthenticatedOnboardingNewProjectPageRouteImport } from './routes/_authenticated/_onboarding/new-project/page'
import { Route as AuthenticatedDashboardWorkspacesPageRouteImport } from './routes/_authenticated/_dashboard/workspaces/page'
import { Route as AuthenticatedDashboardWorkspacePageRouteImport } from './routes/_authenticated/_dashboard/workspace/page'
import { Route as AuthenticatedDashboardV2WorkspacesPageRouteImport } from './routes/_authenticated/_dashboard/v2-workspaces/page'
import { Route as AuthenticatedDashboardTasksPageRouteImport } from './routes/_authenticated/_dashboard/tasks/page'
import { Route as AuthenticatedDashboardDashboardPageRouteImport } from './routes/_authenticated/_dashboard/dashboard/page'
import { Route as AuthenticatedSettingsProjectProjectIdPageRouteImport } from './routes/_authenticated/settings/project/$projectId/page'
import { Route as AuthenticatedSettingsBillingPlansPageRouteImport } from './routes/_authenticated/settings/billing/plans/page'
import { Route as AuthenticatedDashboardWorkspaceWorkspaceIdPageRouteImport } from './routes/_authenticated/_dashboard/workspace/$workspaceId/page'
import { Route as AuthenticatedDashboardV2WorkspaceWorkspaceIdPageRouteImport } from './routes/_authenticated/_dashboard/v2-workspace/$workspaceId/page'
import { Route as AuthenticatedDashboardTasksTaskIdPageRouteImport } from './routes/_authenticated/_dashboard/tasks/$taskId/page'
import { Route as AuthenticatedDashboardProjectProjectIdPageRouteImport } from './routes/_authenticated/_dashboard/project/$projectId/page'
import { Route as AuthenticatedDashboardPendingPendingIdPageRouteImport } from './routes/_authenticated/_dashboard/pending/$pendingId/page'
import { Route as AuthenticatedSettingsProjectProjectIdGeneralPageRouteImport } from './routes/_authenticated/settings/project/$projectId/general/page'
import { Route as AuthenticatedSettingsProjectProjectIdCloudPageRouteImport } from './routes/_authenticated/settings/project/$projectId/cloud/page'
import { Route as AuthenticatedSettingsProjectProjectIdCloudSecretsPageRouteImport } from './routes/_authenticated/settings/project/$projectId/cloud/secrets/page'
import { Route as AuthenticatedDashboardTasksOnedevProjectPathIssueNumberPageRouteImport } from './routes/_authenticated/_dashboard/tasks/onedev.$projectPath.$issueNumber/page'

const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInPageRoute = SignInPageRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrganizationPageRoute = CreateOrganizationPageRouteImport.update({
  id: '/create-organization/',
  path: '/create-organization/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsLayoutRoute =
  AuthenticatedSettingsLayoutRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedOnboardingLayoutRoute =
  AuthenticatedOnboardingLayoutRouteImport.update({
    id: '/_onboarding',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutRoute =
  AuthenticatedDashboardLayoutRouteImport.update({
    id: '/_dashboard',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedSettingsPageRoute =
  AuthenticatedSettingsPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedDashboardV2WorkspaceLayoutRoute =
  AuthenticatedDashboardV2WorkspaceLayoutRouteImport.update({
    id: '/v2-workspace',
    path: '/v2-workspace',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardTasksLayoutRoute =
  AuthenticatedDashboardTasksLayoutRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedSettingsTerminalPageRoute =
  AuthenticatedSettingsTerminalPageRouteImport.update({
    id: '/terminal/',
    path: '/terminal/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsSecurityPageRoute =
  AuthenticatedSettingsSecurityPageRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsRingtonesPageRoute =
  AuthenticatedSettingsRingtonesPageRouteImport.update({
    id: '/ringtones/',
    path: '/ringtones/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsProjectsPageRoute =
  AuthenticatedSettingsProjectsPageRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsPresetsPageRoute =
  AuthenticatedSettingsPresetsPageRouteImport.update({
    id: '/presets/',
    path: '/presets/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsPermissionsPageRoute =
  AuthenticatedSettingsPermissionsPageRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsOrganizationPageRoute =
  AuthenticatedSettingsOrganizationPageRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsModelsPageRoute =
  AuthenticatedSettingsModelsPageRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsKeyboardPageRoute =
  AuthenticatedSettingsKeyboardPageRouteImport.update({
    id: '/keyboard/',
    path: '/keyboard/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsIntegrationsPageRoute =
  AuthenticatedSettingsIntegrationsPageRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsGitPageRoute =
  AuthenticatedSettingsGitPageRouteImport.update({
    id: '/git/',
    path: '/git/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsBillingPageRoute =
  AuthenticatedSettingsBillingPageRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsBehaviorPageRoute =
  AuthenticatedSettingsBehaviorPageRouteImport.update({
    id: '/behavior/',
    path: '/behavior/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsAppearancePageRoute =
  AuthenticatedSettingsAppearancePageRouteImport.update({
    id: '/appearance/',
    path: '/appearance/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsApiKeysPageRoute =
  AuthenticatedSettingsApiKeysPageRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsAgentsPageRoute =
  AuthenticatedSettingsAgentsPageRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsAccountPageRoute =
  AuthenticatedSettingsAccountPageRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedOnboardingWelcomePageRoute =
  AuthenticatedOnboardingWelcomePageRouteImport.update({
    id: '/welcome/',
    path: '/welcome/',
    getParentRoute: () => AuthenticatedOnboardingLayoutRoute,
  } as any)
const AuthenticatedOnboardingNewProjectPageRoute =
  AuthenticatedOnboardingNewProjectPageRouteImport.update({
    id: '/new-project/',
    path: '/new-project/',
    getParentRoute: () => AuthenticatedOnboardingLayoutRoute,
  } as any)
const AuthenticatedDashboardWorkspacesPageRoute =
  AuthenticatedDashboardWorkspacesPageRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardWorkspacePageRoute =
  AuthenticatedDashboardWorkspacePageRouteImport.update({
    id: '/workspace/',
    path: '/workspace/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardV2WorkspacesPageRoute =
  AuthenticatedDashboardV2WorkspacesPageRouteImport.update({
    id: '/v2-workspaces/',
    path: '/v2-workspaces/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardTasksPageRoute =
  AuthenticatedDashboardTasksPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardTasksLayoutRoute,
  } as any)
const AuthenticatedDashboardDashboardPageRoute =
  AuthenticatedDashboardDashboardPageRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedSettingsProjectProjectIdPageRoute =
  AuthenticatedSettingsProjectProjectIdPageRouteImport.update({
    id: '/project/$projectId/',
    path: '/project/$projectId/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsBillingPlansPageRoute =
  AuthenticatedSettingsBillingPlansPageRouteImport.update({
    id: '/billing/plans/',
    path: '/billing/plans/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedDashboardWorkspaceWorkspaceIdPageRoute =
  AuthenticatedDashboardWorkspaceWorkspaceIdPageRouteImport.update({
    id: '/workspace/$workspaceId/',
    path: '/workspace/$workspaceId/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardV2WorkspaceWorkspaceIdPageRoute =
  AuthenticatedDashboardV2WorkspaceWorkspaceIdPageRouteImport.update({
    id: '/$workspaceId/',
    path: '/$workspaceId/',
    getParentRoute: () => AuthenticatedDashboardV2WorkspaceLayoutRoute,
  } as any)
const AuthenticatedDashboardTasksTaskIdPageRoute =
  AuthenticatedDashboardTasksTaskIdPageRouteImport.update({
    id: '/$taskId/',
    path: '/$taskId/',
    getParentRoute: () => AuthenticatedDashboardTasksLayoutRoute,
  } as any)
const AuthenticatedDashboardProjectProjectIdPageRoute =
  AuthenticatedDashboardProjectProjectIdPageRouteImport.update({
    id: '/project/$projectId/',
    path: '/project/$projectId/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardPendingPendingIdPageRoute =
  AuthenticatedDashboardPendingPendingIdPageRouteImport.update({
    id: '/pending/$pendingId/',
    path: '/pending/$pendingId/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedSettingsProjectProjectIdGeneralPageRoute =
  AuthenticatedSettingsProjectProjectIdGeneralPageRouteImport.update({
    id: '/project/$projectId/general/',
    path: '/project/$projectId/general/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsProjectProjectIdCloudPageRoute =
  AuthenticatedSettingsProjectProjectIdCloudPageRouteImport.update({
    id: '/project/$projectId/cloud/',
    path: '/project/$projectId/cloud/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsProjectProjectIdCloudSecretsPageRoute =
  AuthenticatedSettingsProjectProjectIdCloudSecretsPageRouteImport.update({
    id: '/project/$projectId/cloud/secrets/',
    path: '/project/$projectId/cloud/secrets/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedDashboardTasksOnedevProjectPathIssueNumberPageRoute =
  AuthenticatedDashboardTasksOnedevProjectPathIssueNumberPageRouteImport.update(
    {
      id: '/onedev/$projectPath/$issueNumber/',
      path: '/onedev/$projectPath/$issueNumber/',
      getParentRoute: () => AuthenticatedDashboardTasksLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/settings': typeof AuthenticatedSettingsLayoutRouteWithChildren
  '/create-organization/': typeof CreateOrganizationPageRoute
  '/sign-in/': typeof SignInPageRoute
  '/tasks': typeof AuthenticatedDashboardTasksLayoutRouteWithChildren
  '/v2-workspace': typeof AuthenticatedDashboardV2WorkspaceLayoutRouteWithChildren
  '/settings/': typeof AuthenticatedSettingsPageRoute
  '/dashboard/': typeof AuthenticatedDashboardDashboardPageRoute
  '/tasks/': typeof AuthenticatedDashboardTasksPageRoute
  '/v2-workspaces/': typeof AuthenticatedDashboardV2WorkspacesPageRoute
  '/workspace/': typeof AuthenticatedDashboardWorkspacePageRoute
  '/workspaces/': typeof AuthenticatedDashboardWorkspacesPageRoute
  '/new-project/': typeof AuthenticatedOnboardingNewProjectPageRoute
  '/welcome/': typeof AuthenticatedOnboardingWelcomePageRoute
  '/settings/account/': typeof AuthenticatedSettingsAccountPageRoute
  '/settings/agents/': typeof AuthenticatedSettingsAgentsPageRoute
  '/settings/api-keys/': typeof AuthenticatedSettingsApiKeysPageRoute
  '/settings/appearance/': typeof AuthenticatedSettingsAppearancePageRoute
  '/settings/behavior/': typeof AuthenticatedSettingsBehaviorPageRoute
  '/settings/billing/': typeof AuthenticatedSettingsBillingPageRoute
  '/settings/git/': typeof AuthenticatedSettingsGitPageRoute
  '/settings/integrations/': typeof AuthenticatedSettingsIntegrationsPageRoute
  '/settings/keyboard/': typeof AuthenticatedSettingsKeyboardPageRoute
  '/settings/models/': typeof AuthenticatedSettingsModelsPageRoute
  '/settings/organization/': typeof AuthenticatedSettingsOrganizationPageRoute
  '/settings/permissions/': typeof AuthenticatedSettingsPermissionsPageRoute
  '/settings/presets/': typeof AuthenticatedSettingsPresetsPageRoute
  '/settings/projects/': typeof AuthenticatedSettingsProjectsPageRoute
  '/settings/ringtones/': typeof AuthenticatedSettingsRingtonesPageRoute
  '/settings/security/': typeof AuthenticatedSettingsSecurityPageRoute
  '/settings/terminal/': typeof AuthenticatedSettingsTerminalPageRoute
  '/pending/$pendingId/': typeof AuthenticatedDashboardPendingPendingIdPageRoute
  '/project/$projectId/': typeof AuthenticatedDashboardProjectProjectIdPageRoute
  '/tasks/$taskId/': typeof AuthenticatedDashboardTasksTaskIdPageRoute
  '/v2-workspace/$workspaceId/': typeof AuthenticatedDashboardV2WorkspaceWorkspaceIdPageRoute
  '/workspace/$workspaceId/': typeof AuthenticatedDashboardWorkspaceWorkspaceIdPageRoute
  '/settings/billing/plans/': typeof AuthenticatedSettingsBillingPlansPageRoute
  '/settings/project/$projectId/': typeof AuthenticatedSettingsProjectProjectIdPageRoute
  '/settings/project/$projectId/cloud/': typeof AuthenticatedSettingsProjectProjectIdCloudPageRoute
  '/settings/project/$projectId/general/': typeof AuthenticatedSettingsProjectProjectIdGeneralPageRoute
  '/tasks/onedev/$projectPath/$issueNumber/': typeof AuthenticatedDashboardTasksOnedevProjectPathIssueNumberPageRoute
  '/settings/project/$projectId/cloud/secrets/': typeof AuthenticatedSettingsProjectProjectIdCloudSecretsPageRoute
}
export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/create-organization': typeof CreateOrganizationPageRoute
  '/sign-in': typeof SignInPageRoute
  '/v2-workspace': typeof AuthenticatedDashboardV2WorkspaceLayoutRouteWithChildren
  '/settings': typeof AuthenticatedSettingsPageRoute
  '/dashboard': typeof AuthenticatedDashboardDashboardPageRoute
  '/tasks': typeof AuthenticatedDashboardTasksPageRoute
  '/v2-workspaces': typeof AuthenticatedDashboardV2WorkspacesPageRoute
  '/workspace': typeof AuthenticatedDashboardWorkspacePageRoute
  '/workspaces': typeof AuthenticatedDashboardWorkspacesPageRoute
  '/new-project': typeof AuthenticatedOnboardingNewProjectPageRoute
  '/welcome': typeof AuthenticatedOnboardingWelcomePageRoute
  '/settings/account': typeof AuthenticatedSettingsAccountPageRoute
  '/settings/agents': typeof AuthenticatedSettingsAgentsPageRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysPageRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearancePageRoute
  '/settings/behavior': typeof AuthenticatedSettingsBehaviorPageRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingPageRoute
  '/settings/git': typeof AuthenticatedSettingsGitPageRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsPageRoute
  '/settings/keyboard': typeof AuthenticatedSettingsKeyboardPageRoute
  '/settings/models': typeof AuthenticatedSettingsModelsPageRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationPageRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsPageRoute
  '/settings/presets': typeof AuthenticatedSettingsPresetsPageRoute
  '/settings/projects': typeof AuthenticatedSettingsProjectsPageRoute
  '/settings/ringtones': typeof AuthenticatedSettingsRingtonesPageRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityPageRoute
  '/settings/terminal': typeof AuthenticatedSettingsTerminalPageRoute
  '/pending/$pendingId': typeof AuthenticatedDashboardPendingPendingIdPageRoute
  '/project/$projectId': typeof AuthenticatedDashboardProjectProjectIdPageRoute
  '/tasks/$taskId': typeof AuthenticatedDashboardTasksTaskIdPageRoute
  '/v2-workspace/$workspaceId': typeof AuthenticatedDashboardV2WorkspaceWorkspaceIdPageRoute
  '/workspace/$workspaceId': typeof AuthenticatedDashboardWorkspaceWorkspaceIdPageRoute
  '/settings/billing/plans': typeof AuthenticatedSettingsBillingPlansPageRoute
  '/settings/project/$projectId': typeof AuthenticatedSettingsProjectProjectIdPageRoute
  '/settings/project/$projectId/cloud': typeof AuthenticatedSettingsProjectProjectIdCloudPageRoute
  '/settings/project/$projectId/general': typeof AuthenticatedSettingsProjectProjectIdGeneralPageRoute
  '/tasks/onedev/$projectPath/$issueNumber': typeof AuthenticatedDashboardTasksOnedevProjectPathIssueNumberPageRoute
  '/settings/project/$projectId/cloud/secrets': typeof AuthenticatedSettingsProjectProjectIdCloudSecretsPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/_authenticated': typeof AuthenticatedLayoutRouteWithChildren
  '/_authenticated/_dashboard': typeof AuthenticatedDashboardLayoutRouteWithChildren
  '/_authenticated/_onboarding': typeof AuthenticatedOnboardingLayoutRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsLayoutRouteWithChildren
  '/create-organization/': typeof CreateOrganizationPageRoute
  '/sign-in/': typeof SignInPageRoute
  '/_authenticated/_dashboard/tasks': typeof AuthenticatedDashboardTasksLayoutRouteWithChildren
  '/_authenticated/_dashboard/v2-workspace': typeof AuthenticatedDashboardV2WorkspaceLayoutRouteWithChildren
  '/_authenticated/settings/': typeof AuthenticatedSettingsPageRoute
  '/_authenticated/_dashboard/dashboard/': typeof AuthenticatedDashboardDashboardPageRoute
  '/_authenticated/_dashboard/tasks/': typeof AuthenticatedDashboardTasksPageRoute
  '/_authenticated/_dashboard/v2-workspaces/': typeof AuthenticatedDashboardV2WorkspacesPageRoute
  '/_authenticated/_dashboard/workspace/': typeof AuthenticatedDashboardWorkspacePageRoute
  '/_authenticated/_dashboard/workspaces/': typeof AuthenticatedDashboardWorkspacesPageRoute
  '/_authenticated/_onboarding/new-project/': typeof AuthenticatedOnboardingNewProjectPageRoute
  '/_authenticated/_onboarding/welcome/': typeof AuthenticatedOnboardingWelcomePageRoute
  '/_authenticated/settings/account/': typeof AuthenticatedSettingsAccountPageRoute
  '/_authenticated/settings/agents/': typeof AuthenticatedSettingsAgentsPageRoute
  '/_authenticated/settings/api-keys/': typeof AuthenticatedSettingsApiKeysPageRoute
  '/_authenticated/settings/appearance/': typeof AuthenticatedSettingsAppearancePageRoute
  '/_authenticated/settings/behavior/': typeof AuthenticatedSettingsBehaviorPageRoute
  '/_authenticated/settings/billing/': typeof AuthenticatedSettingsBillingPageRoute
  '/_authenticated/settings/git/': typeof AuthenticatedSettingsGitPageRoute
  '/_authenticated/settings/integrations/': typeof AuthenticatedSettingsIntegrationsPageRoute
  '/_authenticated/settings/keyboard/': typeof AuthenticatedSettingsKeyboardPageRoute
  '/_authenticated/settings/models/': typeof AuthenticatedSettingsModelsPageRoute
  '/_authenticated/settings/organization/': typeof AuthenticatedSettingsOrganizationPageRoute
  '/_authenticated/settings/permissions/': typeof AuthenticatedSettingsPermissionsPageRoute
  '/_authenticated/settings/presets/': typeof AuthenticatedSettingsPresetsPageRoute
  '/_authenticated/settings/projects/': typeof AuthenticatedSettingsProjectsPageRoute
  '/_authenticated/settings/ringtones/': typeof AuthenticatedSettingsRingtonesPageRoute
  '/_authenticated/settings/security/': typeof AuthenticatedSettingsSecurityPageRoute
  '/_authenticated/settings/terminal/': typeof AuthenticatedSettingsTerminalPageRoute
  '/_authenticated/_dashboard/pending/$pendingId/': typeof AuthenticatedDashboardPendingPendingIdPageRoute
  '/_authenticated/_dashboard/project/$projectId/': typeof AuthenticatedDashboardProjectProjectIdPageRoute
  '/_authenticated/_dashboard/tasks/$taskId/': typeof AuthenticatedDashboardTasksTaskIdPageRoute
  '/_authenticated/_dashboard/v2-workspace/$workspaceId/': typeof AuthenticatedDashboardV2WorkspaceWorkspaceIdPageRoute
  '/_authenticated/_dashboard/workspace/$workspaceId/': typeof AuthenticatedDashboardWorkspaceWorkspaceIdPageRoute
  '/_authenticated/settings/billing/plans/': typeof AuthenticatedSettingsBillingPlansPageRoute
  '/_authenticated/settings/project/$projectId/': typeof AuthenticatedSettingsProjectProjectIdPageRoute
  '/_authenticated/settings/project/$projectId/cloud/': typeof AuthenticatedSettingsProjectProjectIdCloudPageRoute
  '/_authenticated/settings/project/$projectId/general/': typeof AuthenticatedSettingsProjectProjectIdGeneralPageRoute
  '/_authenticated/_dashboard/tasks/onedev/$projectPath/$issueNumber/': typeof AuthenticatedDashboardTasksOnedevProjectPathIssueNumberPageRoute
  '/_authenticated/settings/project/$projectId/cloud/secrets/': typeof AuthenticatedSettingsProjectProjectIdCloudSecretsPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/create-organization/'
    | '/sign-in/'
    | '/tasks'
    | '/v2-workspace'
    | '/settings/'
    | '/dashboard/'
    | '/tasks/'
    | '/v2-workspaces/'
    | '/workspace/'
    | '/workspaces/'
    | '/new-project/'
    | '/welcome/'
    | '/settings/account/'
    | '/settings/agents/'
    | '/settings/api-keys/'
    | '/settings/appearance/'
    | '/settings/behavior/'
    | '/settings/billing/'
    | '/settings/git/'
    | '/settings/integrations/'
    | '/settings/keyboard/'
    | '/settings/models/'
    | '/settings/organization/'
    | '/settings/permissions/'
    | '/settings/presets/'
    | '/settings/projects/'
    | '/settings/ringtones/'
    | '/settings/security/'
    | '/settings/terminal/'
    | '/pending/$pendingId/'
    | '/project/$projectId/'
    | '/tasks/$taskId/'
    | '/v2-workspace/$workspaceId/'
    | '/workspace/$workspaceId/'
    | '/settings/billing/plans/'
    | '/settings/project/$projectId/'
    | '/settings/project/$projectId/cloud/'
    | '/settings/project/$projectId/general/'
    | '/tasks/onedev/$projectPath/$issueNumber/'
    | '/settings/project/$projectId/cloud/secrets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-organization'
    | '/sign-in'
    | '/v2-workspace'
    | '/settings'
    | '/dashboard'
    | '/tasks'
    | '/v2-workspaces'
    | '/workspace'
    | '/workspaces'
    | '/new-project'
    | '/welcome'
    | '/settings/account'
    | '/settings/agents'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/behavior'
    | '/settings/billing'
    | '/settings/git'
    | '/settings/integrations'
    | '/settings/keyboard'
    | '/settings/models'
    | '/settings/organization'
    | '/settings/permissions'
    | '/settings/presets'
    | '/settings/projects'
    | '/settings/ringtones'
    | '/settings/security'
    | '/settings/terminal'
    | '/pending/$pendingId'
    | '/project/$projectId'
    | '/tasks/$taskId'
    | '/v2-workspace/$workspaceId'
    | '/workspace/$workspaceId'
    | '/settings/billing/plans'
    | '/settings/project/$projectId'
    | '/settings/project/$projectId/cloud'
    | '/settings/project/$projectId/general'
    | '/tasks/onedev/$projectPath/$issueNumber'
    | '/settings/project/$projectId/cloud/secrets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_dashboard'
    | '/_authenticated/_onboarding'
    | '/_authenticated/settings'
    | '/create-organization/'
    | '/sign-in/'
    | '/_authenticated/_dashboard/tasks'
    | '/_authenticated/_dashboard/v2-workspace'
    | '/_authenticated/settings/'
    | '/_authenticated/_dashboard/dashboard/'
    | '/_authenticated/_dashboard/tasks/'
    | '/_authenticated/_dashboard/v2-workspaces/'
    | '/_authenticated/_dashboard/workspace/'
    | '/_authenticated/_dashboard/workspaces/'
    | '/_authenticated/_onboarding/new-project/'
    | '/_authenticated/_onboarding/welcome/'
    | '/_authenticated/settings/account/'
    | '/_authenticated/settings/agents/'
    | '/_authenticated/settings/api-keys/'
    | '/_authenticated/settings/appearance/'
    | '/_authenticated/settings/behavior/'
    | '/_authenticated/settings/billing/'
    | '/_authenticated/settings/git/'
    | '/_authenticated/settings/integrations/'
    | '/_authenticated/settings/keyboard/'
    | '/_authenticated/settings/models/'
    | '/_authenticated/settings/organization/'
    | '/_authenticated/settings/permissions/'
    | '/_authenticated/settings/presets/'
    | '/_authenticated/settings/projects/'
    | '/_authenticated/settings/ringtones/'
    | '/_authenticated/settings/security/'
    | '/_authenticated/settings/terminal/'
    | '/_authenticated/_dashboard/pending/$pendingId/'
    | '/_authenticated/_dashboard/project/$projectId/'
    | '/_authenticated/_dashboard/tasks/$taskId/'
    | '/_authenticated/_dashboard/v2-workspace/$workspaceId/'
    | '/_authenticated/_dashboard/workspace/$workspaceId/'
    | '/_authenticated/settings/billing/plans/'
    | '/_authenticated/settings/project/$projectId/'
    | '/_authenticated/settings/project/$projectId/cloud/'
    | '/_authenticated/settings/project/$projectId/general/'
    | '/_authenticated/_dashboard/tasks/onedev/$projectPath/$issueNumber/'
    | '/_authenticated/settings/project/$projectId/cloud/secrets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  CreateOrganizationPageRoute: typeof CreateOrganizationPageRoute
  SignInPageRoute: typeof SignInPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-organization/': {
      id: '/create-organization/'
      path: '/create-organization'
      fullPath: '/create-organization/'
      preLoaderRoute: typeof CreateOrganizationPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_onboarding': {
      id: '/_authenticated/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedOnboardingLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_dashboard': {
      id: '/_authenticated/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/_dashboard/v2-workspace': {
      id: '/_authenticated/_dashboard/v2-workspace'
      path: '/v2-workspace'
      fullPath: '/v2-workspace'
      preLoaderRoute: typeof AuthenticatedDashboardV2WorkspaceLayoutRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard/tasks': {
      id: '/_authenticated/_dashboard/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedDashboardTasksLayoutRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/settings/terminal/': {
      id: '/_authenticated/settings/terminal/'
      path: '/terminal'
      fullPath: '/settings/terminal/'
      preLoaderRoute: typeof AuthenticatedSettingsTerminalPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/security/': {
      id: '/_authenticated/settings/security/'
      path: '/security'
      fullPath: '/settings/security/'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/ringtones/': {
      id: '/_authenticated/settings/ringtones/'
      path: '/ringtones'
      fullPath: '/settings/ringtones/'
      preLoaderRoute: typeof AuthenticatedSettingsRingtonesPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/projects/': {
      id: '/_authenticated/settings/projects/'
      path: '/projects'
      fullPath: '/settings/projects/'
      preLoaderRoute: typeof AuthenticatedSettingsProjectsPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/presets/': {
      id: '/_authenticated/settings/presets/'
      path: '/presets'
      fullPath: '/settings/presets/'
      preLoaderRoute: typeof AuthenticatedSettingsPresetsPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/permissions/': {
      id: '/_authenticated/settings/permissions/'
      path: '/permissions'
      fullPath: '/settings/permissions/'
      preLoaderRoute: typeof AuthenticatedSettingsPermissionsPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/organization/': {
      id: '/_authenticated/settings/organization/'
      path: '/organization'
      fullPath: '/settings/organization/'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/models/': {
      id: '/_authenticated/settings/models/'
      path: '/models'
      fullPath: '/settings/models/'
      preLoaderRoute: typeof AuthenticatedSettingsModelsPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/keyboard/': {
      id: '/_authenticated/settings/keyboard/'
      path: '/keyboard'
      fullPath: '/settings/keyboard/'
      preLoaderRoute: typeof AuthenticatedSettingsKeyboardPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/integrations/': {
      id: '/_authenticated/settings/integrations/'
      path: '/integrations'
      fullPath: '/settings/integrations/'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/git/': {
      id: '/_authenticated/settings/git/'
      path: '/git'
      fullPath: '/settings/git/'
      preLoaderRoute: typeof AuthenticatedSettingsGitPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/billing/': {
      id: '/_authenticated/settings/billing/'
      path: '/billing'
      fullPath: '/settings/billing/'
      preLoaderRoute: typeof AuthenticatedSettingsBillingPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/behavior/': {
      id: '/_authenticated/settings/behavior/'
      path: '/behavior'
      fullPath: '/settings/behavior/'
      preLoaderRoute: typeof AuthenticatedSettingsBehaviorPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/appearance/': {
      id: '/_authenticated/settings/appearance/'
      path: '/appearance'
      fullPath: '/settings/appearance/'
      preLoaderRoute: typeof AuthenticatedSettingsAppearancePageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/api-keys/': {
      id: '/_authenticated/settings/api-keys/'
      path: '/api-keys'
      fullPath: '/settings/api-keys/'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/agents/': {
      id: '/_authenticated/settings/agents/'
      path: '/agents'
      fullPath: '/settings/agents/'
      preLoaderRoute: typeof AuthenticatedSettingsAgentsPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/account/': {
      id: '/_authenticated/settings/account/'
      path: '/account'
      fullPath: '/settings/account/'
      preLoaderRoute: typeof AuthenticatedSettingsAccountPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/_onboarding/welcome/': {
      id: '/_authenticated/_onboarding/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof AuthenticatedOnboardingWelcomePageRouteImport
      parentRoute: typeof AuthenticatedOnboardingLayoutRoute
    }
    '/_authenticated/_onboarding/new-project/': {
      id: '/_authenticated/_onboarding/new-project/'
      path: '/new-project'
      fullPath: '/new-project/'
      preLoaderRoute: typeof AuthenticatedOnboardingNewProjectPageRouteImport
      parentRoute: typeof AuthenticatedOnboardingLayoutRoute
    }
    '/_authenticated/_dashboard/workspaces/': {
      id: '/_authenticated/_dashboard/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedDashboardWorkspacesPageRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard/workspace/': {
      id: '/_authenticated/_dashboard/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AuthenticatedDashboardWorkspacePageRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard/v2-workspaces/': {
      id: '/_authenticated/_dashboard/v2-workspaces/'
      path: '/v2-workspaces'
      fullPath: '/v2-workspaces/'
      preLoaderRoute: typeof AuthenticatedDashboardV2WorkspacesPageRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard/tasks/': {
      id: '/_authenticated/_dashboard/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedDashboardTasksPageRouteImport
      parentRoute: typeof AuthenticatedDashboardTasksLayoutRoute
    }
    '/_authenticated/_dashboard/dashboard/': {
      id: '/_authenticated/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardPageRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/settings/project/$projectId/': {
      id: '/_authenticated/settings/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/settings/project/$projectId/'
      preLoaderRoute: typeof AuthenticatedSettingsProjectProjectIdPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/billing/plans/': {
      id: '/_authenticated/settings/billing/plans/'
      path: '/billing/plans'
      fullPath: '/settings/billing/plans/'
      preLoaderRoute: typeof AuthenticatedSettingsBillingPlansPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/_dashboard/workspace/$workspaceId/': {
      id: '/_authenticated/_dashboard/workspace/$workspaceId/'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedDashboardWorkspaceWorkspaceIdPageRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard/v2-workspace/$workspaceId/': {
      id: '/_authenticated/_dashboard/v2-workspace/$workspaceId/'
      path: '/$workspaceId'
      fullPath: '/v2-workspace/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedDashboardV2WorkspaceWorkspaceIdPageRouteImport
      parentRoute: typeof AuthenticatedDashboardV2WorkspaceLayoutRoute
    }
    '/_authenticated/_dashboard/tasks/$taskId/': {
      id: '/_authenticated/_dashboard/tasks/$taskId/'
      path: '/$taskId'
      fullPath: '/tasks/$taskId/'
      preLoaderRoute: typeof AuthenticatedDashboardTasksTaskIdPageRouteImport
      parentRoute: typeof AuthenticatedDashboardTasksLayoutRoute
    }
    '/_authenticated/_dashboard/project/$projectId/': {
      id: '/_authenticated/_dashboard/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof AuthenticatedDashboardProjectProjectIdPageRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard/pending/$pendingId/': {
      id: '/_authenticated/_dashboard/pending/$pendingId/'
      path: '/pending/$pendingId'
      fullPath: '/pending/$pendingId/'
      preLoaderRoute: typeof AuthenticatedDashboardPendingPendingIdPageRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/settings/project/$projectId/general/': {
      id: '/_authenticated/settings/project/$projectId/general/'
      path: '/project/$projectId/general'
      fullPath: '/settings/project/$projectId/general/'
      preLoaderRoute: typeof AuthenticatedSettingsProjectProjectIdGeneralPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/project/$projectId/cloud/': {
      id: '/_authenticated/settings/project/$projectId/cloud/'
      path: '/project/$projectId/cloud'
      fullPath: '/settings/project/$projectId/cloud/'
      preLoaderRoute: typeof AuthenticatedSettingsProjectProjectIdCloudPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/project/$projectId/cloud/secrets/': {
      id: '/_authenticated/settings/project/$projectId/cloud/secrets/'
      path: '/project/$projectId/cloud/secrets'
      fullPath: '/settings/project/$projectId/cloud/secrets/'
      preLoaderRoute: typeof AuthenticatedSettingsProjectProjectIdCloudSecretsPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/_dashboard/tasks/onedev/$projectPath/$issueNumber/': {
      id: '/_authenticated/_dashboard/tasks/onedev/$projectPath/$issueNumber/'
      path: '/onedev/$projectPath/$issueNumber'
      fullPath: '/tasks/onedev/$projectPath/$issueNumber/'
      preLoaderRoute: typeof AuthenticatedDashboardTasksOnedevProjectPathIssueNumberPageRouteImport
      parentRoute: typeof AuthenticatedDashboardTasksLayoutRoute
    }
  }
}

interface AuthenticatedDashboardTasksLayoutRouteChildren {
  AuthenticatedDashboardTasksPageRoute: typeof AuthenticatedDashboardTasksPageRoute
  AuthenticatedDashboardTasksTaskIdPageRoute: typeof AuthenticatedDashboardTasksTaskIdPageRoute
  AuthenticatedDashboardTasksOnedevProjectPathIssueNumberPageRoute: typeof AuthenticatedDashboardTasksOnedevProjectPathIssueNumberPageRoute
}

const AuthenticatedDashboardTasksLayoutRouteChildren: AuthenticatedDashboardTasksLayoutRouteChildren =
  {
    AuthenticatedDashboardTasksPageRoute: AuthenticatedDashboardTasksPageRoute,
    AuthenticatedDashboardTasksTaskIdPageRoute:
      AuthenticatedDashboardTasksTaskIdPageRoute,
    AuthenticatedDashboardTasksOnedevProjectPathIssueNumberPageRoute:
      AuthenticatedDashboardTasksOnedevProjectPathIssueNumberPageRoute,
  }

const AuthenticatedDashboardTasksLayoutRouteWithChildren =
  AuthenticatedDashboardTasksLayoutRoute._addFileChildren(
    AuthenticatedDashboardTasksLayoutRouteChildren,
  )

interface AuthenticatedDashboardV2WorkspaceLayoutRouteChildren {
  AuthenticatedDashboardV2WorkspaceWorkspaceIdPageRoute: typeof AuthenticatedDashboardV2WorkspaceWorkspaceIdPageRoute
}

const AuthenticatedDashboardV2WorkspaceLayoutRouteChildren: AuthenticatedDashboardV2WorkspaceLayoutRouteChildren =
  {
    AuthenticatedDashboardV2WorkspaceWorkspaceIdPageRoute:
      AuthenticatedDashboardV2WorkspaceWorkspaceIdPageRoute,
  }

const AuthenticatedDashboardV2WorkspaceLayoutRouteWithChildren =
  AuthenticatedDashboardV2WorkspaceLayoutRoute._addFileChildren(
    AuthenticatedDashboardV2WorkspaceLayoutRouteChildren,
  )

interface AuthenticatedDashboardLayoutRouteChildren {
  AuthenticatedDashboardTasksLayoutRoute: typeof AuthenticatedDashboardTasksLayoutRouteWithChildren
  AuthenticatedDashboardV2WorkspaceLayoutRoute: typeof AuthenticatedDashboardV2WorkspaceLayoutRouteWithChildren
  AuthenticatedDashboardDashboardPageRoute: typeof AuthenticatedDashboardDashboardPageRoute
  AuthenticatedDashboardV2WorkspacesPageRoute: typeof AuthenticatedDashboardV2WorkspacesPageRoute
  AuthenticatedDashboardWorkspacePageRoute: typeof AuthenticatedDashboardWorkspacePageRoute
  AuthenticatedDashboardWorkspacesPageRoute: typeof AuthenticatedDashboardWorkspacesPageRoute
  AuthenticatedDashboardPendingPendingIdPageRoute: typeof AuthenticatedDashboardPendingPendingIdPageRoute
  AuthenticatedDashboardProjectProjectIdPageRoute: typeof AuthenticatedDashboardProjectProjectIdPageRoute
  AuthenticatedDashboardWorkspaceWorkspaceIdPageRoute: typeof AuthenticatedDashboardWorkspaceWorkspaceIdPageRoute
}

const AuthenticatedDashboardLayoutRouteChildren: AuthenticatedDashboardLayoutRouteChildren =
  {
    AuthenticatedDashboardTasksLayoutRoute:
      AuthenticatedDashboardTasksLayoutRouteWithChildren,
    AuthenticatedDashboardV2WorkspaceLayoutRoute:
      AuthenticatedDashboardV2WorkspaceLayoutRouteWithChildren,
    AuthenticatedDashboardDashboardPageRoute:
      AuthenticatedDashboardDashboardPageRoute,
    AuthenticatedDashboardV2WorkspacesPageRoute:
      AuthenticatedDashboardV2WorkspacesPageRoute,
    AuthenticatedDashboardWorkspacePageRoute:
      AuthenticatedDashboardWorkspacePageRoute,
    AuthenticatedDashboardWorkspacesPageRoute:
      AuthenticatedDashboardWorkspacesPageRoute,
    AuthenticatedDashboardPendingPendingIdPageRoute:
      AuthenticatedDashboardPendingPendingIdPageRoute,
    AuthenticatedDashboardProjectProjectIdPageRoute:
      AuthenticatedDashboardProjectProjectIdPageRoute,
    AuthenticatedDashboardWorkspaceWorkspaceIdPageRoute:
      AuthenticatedDashboardWorkspaceWorkspaceIdPageRoute,
  }

const AuthenticatedDashboardLayoutRouteWithChildren =
  AuthenticatedDashboardLayoutRoute._addFileChildren(
    AuthenticatedDashboardLayoutRouteChildren,
  )

interface AuthenticatedOnboardingLayoutRouteChildren {
  AuthenticatedOnboardingNewProjectPageRoute: typeof AuthenticatedOnboardingNewProjectPageRoute
  AuthenticatedOnboardingWelcomePageRoute: typeof AuthenticatedOnboardingWelcomePageRoute
}

const AuthenticatedOnboardingLayoutRouteChildren: AuthenticatedOnboardingLayoutRouteChildren =
  {
    AuthenticatedOnboardingNewProjectPageRoute:
      AuthenticatedOnboardingNewProjectPageRoute,
    AuthenticatedOnboardingWelcomePageRoute:
      AuthenticatedOnboardingWelcomePageRoute,
  }

const AuthenticatedOnboardingLayoutRouteWithChildren =
  AuthenticatedOnboardingLayoutRoute._addFileChildren(
    AuthenticatedOnboardingLayoutRouteChildren,
  )

interface AuthenticatedSettingsLayoutRouteChildren {
  AuthenticatedSettingsPageRoute: typeof AuthenticatedSettingsPageRoute
  AuthenticatedSettingsAccountPageRoute: typeof AuthenticatedSettingsAccountPageRoute
  AuthenticatedSettingsAgentsPageRoute: typeof AuthenticatedSettingsAgentsPageRoute
  AuthenticatedSettingsApiKeysPageRoute: typeof AuthenticatedSettingsApiKeysPageRoute
  AuthenticatedSettingsAppearancePageRoute: typeof AuthenticatedSettingsAppearancePageRoute
  AuthenticatedSettingsBehaviorPageRoute: typeof AuthenticatedSettingsBehaviorPageRoute
  AuthenticatedSettingsBillingPageRoute: typeof AuthenticatedSettingsBillingPageRoute
  AuthenticatedSettingsGitPageRoute: typeof AuthenticatedSettingsGitPageRoute
  AuthenticatedSettingsIntegrationsPageRoute: typeof AuthenticatedSettingsIntegrationsPageRoute
  AuthenticatedSettingsKeyboardPageRoute: typeof AuthenticatedSettingsKeyboardPageRoute
  AuthenticatedSettingsModelsPageRoute: typeof AuthenticatedSettingsModelsPageRoute
  AuthenticatedSettingsOrganizationPageRoute: typeof AuthenticatedSettingsOrganizationPageRoute
  AuthenticatedSettingsPermissionsPageRoute: typeof AuthenticatedSettingsPermissionsPageRoute
  AuthenticatedSettingsPresetsPageRoute: typeof AuthenticatedSettingsPresetsPageRoute
  AuthenticatedSettingsProjectsPageRoute: typeof AuthenticatedSettingsProjectsPageRoute
  AuthenticatedSettingsRingtonesPageRoute: typeof AuthenticatedSettingsRingtonesPageRoute
  AuthenticatedSettingsSecurityPageRoute: typeof AuthenticatedSettingsSecurityPageRoute
  AuthenticatedSettingsTerminalPageRoute: typeof AuthenticatedSettingsTerminalPageRoute
  AuthenticatedSettingsBillingPlansPageRoute: typeof AuthenticatedSettingsBillingPlansPageRoute
  AuthenticatedSettingsProjectProjectIdPageRoute: typeof AuthenticatedSettingsProjectProjectIdPageRoute
  AuthenticatedSettingsProjectProjectIdCloudPageRoute: typeof AuthenticatedSettingsProjectProjectIdCloudPageRoute
  AuthenticatedSettingsProjectProjectIdGeneralPageRoute: typeof AuthenticatedSettingsProjectProjectIdGeneralPageRoute
  AuthenticatedSettingsProjectProjectIdCloudSecretsPageRoute: typeof AuthenticatedSettingsProjectProjectIdCloudSecretsPageRoute
}

const AuthenticatedSettingsLayoutRouteChildren: AuthenticatedSettingsLayoutRouteChildren =
  {
    AuthenticatedSettingsPageRoute: AuthenticatedSettingsPageRoute,
    AuthenticatedSettingsAccountPageRoute:
      AuthenticatedSettingsAccountPageRoute,
    AuthenticatedSettingsAgentsPageRoute: AuthenticatedSettingsAgentsPageRoute,
    AuthenticatedSettingsApiKeysPageRoute:
      AuthenticatedSettingsApiKeysPageRoute,
    AuthenticatedSettingsAppearancePageRoute:
      AuthenticatedSettingsAppearancePageRoute,
    AuthenticatedSettingsBehaviorPageRoute:
      AuthenticatedSettingsBehaviorPageRoute,
    AuthenticatedSettingsBillingPageRoute:
      AuthenticatedSettingsBillingPageRoute,
    AuthenticatedSettingsGitPageRoute: AuthenticatedSettingsGitPageRoute,
    AuthenticatedSettingsIntegrationsPageRoute:
      AuthenticatedSettingsIntegrationsPageRoute,
    AuthenticatedSettingsKeyboardPageRoute:
      AuthenticatedSettingsKeyboardPageRoute,
    AuthenticatedSettingsModelsPageRoute: AuthenticatedSettingsModelsPageRoute,
    AuthenticatedSettingsOrganizationPageRoute:
      AuthenticatedSettingsOrganizationPageRoute,
    AuthenticatedSettingsPermissionsPageRoute:
      AuthenticatedSettingsPermissionsPageRoute,
    AuthenticatedSettingsPresetsPageRoute:
      AuthenticatedSettingsPresetsPageRoute,
    AuthenticatedSettingsProjectsPageRoute:
      AuthenticatedSettingsProjectsPageRoute,
    AuthenticatedSettingsRingtonesPageRoute:
      AuthenticatedSettingsRingtonesPageRoute,
    AuthenticatedSettingsSecurityPageRoute:
      AuthenticatedSettingsSecurityPageRoute,
    AuthenticatedSettingsTerminalPageRoute:
      AuthenticatedSettingsTerminalPageRoute,
    AuthenticatedSettingsBillingPlansPageRoute:
      AuthenticatedSettingsBillingPlansPageRoute,
    AuthenticatedSettingsProjectProjectIdPageRoute:
      AuthenticatedSettingsProjectProjectIdPageRoute,
    AuthenticatedSettingsProjectProjectIdCloudPageRoute:
      AuthenticatedSettingsProjectProjectIdCloudPageRoute,
    AuthenticatedSettingsProjectProjectIdGeneralPageRoute:
      AuthenticatedSettingsProjectProjectIdGeneralPageRoute,
    AuthenticatedSettingsProjectProjectIdCloudSecretsPageRoute:
      AuthenticatedSettingsProjectProjectIdCloudSecretsPageRoute,
  }

const AuthenticatedSettingsLayoutRouteWithChildren =
  AuthenticatedSettingsLayoutRoute._addFileChildren(
    AuthenticatedSettingsLayoutRouteChildren,
  )

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedDashboardLayoutRoute: typeof AuthenticatedDashboardLayoutRouteWithChildren
  AuthenticatedOnboardingLayoutRoute: typeof AuthenticatedOnboardingLayoutRouteWithChildren
  AuthenticatedSettingsLayoutRoute: typeof AuthenticatedSettingsLayoutRouteWithChildren
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedDashboardLayoutRoute:
    AuthenticatedDashboardLayoutRouteWithChildren,
  AuthenticatedOnboardingLayoutRoute:
    AuthenticatedOnboardingLayoutRouteWithChildren,
  AuthenticatedSettingsLayoutRoute:
    AuthenticatedSettingsLayoutRouteWithChildren,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  CreateOrganizationPageRoute: CreateOrganizationPageRoute,
  SignInPageRoute: SignInPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
