import { z } from "zod";

const attachmentSchema = z.object({
	data: z.string(),
	mediaType: z.string(),
	filename: z.string().optional(),
});

const linkedContextSchema = z
	.object({
		internalIssueIds: z.array(z.string()).optional(),
		githubIssueUrls: z.array(z.string()).optional(),
		linkedPrUrl: z.string().optional(),
		attachments: z.array(attachmentSchema).optional(),
	})
	.optional();

export const getContextInputSchema = z.object({ projectId: z.string() });

export const searchBranchesInputSchema = z.object({
	projectId: z.string(),
	query: z.string().optional(),
	cursor: z.string().optional(),
	limit: z.number().min(1).max(200).optional(),
	refresh: z.boolean().optional(),
	filter: z.enum(["branch", "worktree"]).optional(),
});

export const generateBranchNameInputSchema = z.object({
	projectId: z.string(),
	prompt: z.string(),
});

export const getProgressInputSchema = z.object({ pendingId: z.string() });

export const createInputSchema = z.object({
	pendingId: z.string(),
	projectId: z.string(),
	names: z.object({
		workspaceName: z.string(),
		branchName: z.string(),
		// Renderer signal: true when `workspaceName` came from the
		// friendly-random fallback (no user-typed title). Gates the
		// post-create AI rename so a user-typed title is never
		// overwritten. Optional for backcompat — defaults to allowing
		// the rename, matching pre-field behavior.
		workspaceNameWasAutoGenerated: z.boolean().optional(),
	}),
	composer: z.object({
		prompt: z.string().optional(),
		baseBranch: z.string().optional(),
		// Hint from the picker about which form of the base branch
		// was selected. When provided, the server uses it directly
		// instead of probing — avoids racing against stale cached
		// remote refs that could win in a re-resolve. See
		// `resolve-start-point.ts` for the fallback semantics.
		baseBranchSource: z.enum(["local", "remote-tracking"]).optional(),
		runSetupScript: z.boolean().optional(),
	}),
	linkedContext: linkedContextSchema,
});

const checkoutPrSchema = z.object({
	number: z.number().int().positive(),
	url: z.string().url(),
	title: z.string(),
	headRefName: z.string(),
	baseRefName: z.string(),
	headRepositoryOwner: z.string(),
	isCrossRepository: z.boolean(),
	state: z.enum(["open", "closed", "merged"]),
});

export const checkoutInputSchema = z
	.object({
		pendingId: z.string(),
		projectId: z.string(),
		workspaceName: z.string(),
		// Exactly one of `branch` or `pr` must be set (refine below).
		// Branch mode: caller supplies a branch name; server resolves it.
		// PR mode: caller supplies PR metadata + runs `gh pr checkout`.
		branch: z.string().optional(),
		pr: checkoutPrSchema.optional(),
		composer: z.object({
			prompt: z.string().optional(),
			// Written to `branch.<name>.base` for the Changes tab. Client
			// fills from picker in branch mode, or `pr.baseRefName` in PR
			// mode. Server reads uniformly — no intent branching for this
			// write.
			baseBranch: z.string().optional(),
			runSetupScript: z.boolean().optional(),
		}),
		linkedContext: linkedContextSchema,
	})
	.refine((value) => Boolean(value.branch) !== Boolean(value.pr), {
		message: "exactly one of `branch` or `pr` must be set",
	});

export const adoptInputSchema = z.object({
	projectId: z.string(),
	workspaceName: z.string(),
	branch: z.string(),
	// When provided, adopt the worktree at this explicit path instead
	// of looking one up under <repoPath>/.worktrees/<branch>. Used by
	// the v1→v2 migration to adopt worktrees at legacy paths (e.g.
	// ~/.superset/worktrees/...) that aren't under the picker's
	// Superset-managed prefix.
	worktreePath: z.string().optional(),
});

export const githubSearchInputSchema = z.object({
	projectId: z.string(),
	query: z.string().optional(),
	limit: z.number().min(1).max(100).optional(),
	includeClosed: z.boolean().optional(),
});

export const githubIssueContentInputSchema = z.object({
	projectId: z.string(),
	issueNumber: z.number().int().positive(),
});

export const githubPullRequestContentInputSchema = z.object({
	projectId: z.string(),
	prNumber: z.number().int().positive(),
});

export const issueContentSchema = z.object({
	number: z.number(),
	title: z.string(),
	body: z.string().nullable().optional(),
	url: z.string(),
	state: z.string(),
	author: z.object({ login: z.string() }).optional(),
	createdAt: z.string().optional(),
	updatedAt: z.string().optional(),
});

export const pullRequestContentSchema = z.object({
	number: z.number(),
	title: z.string(),
	body: z.string().nullable().optional(),
	url: z.string(),
	state: z.string(),
	headRefName: z.string(),
	baseRefName: z.string(),
	// `gh pr view` returns null when the PR's head fork repository has been
	// deleted. Nullable so the schema parse doesn't fail; consumers decide
	// how to handle a missing owner (client surfaces a clear error for
	// cross-repo PRs — same-repo PRs shouldn't see null in practice).
	headRepositoryOwner: z.object({ login: z.string() }).nullable(),
	isCrossRepository: z.boolean(),
	isDraft: z.boolean(),
	author: z.object({ login: z.string() }).optional(),
	createdAt: z.string().optional(),
	updatedAt: z.string().optional(),
});
