import { homedir } from "node:os";
import { join } from "node:path";

/** Mount target for the generated container superset-home (read-only). */
export const CONTAINER_SUPERSET_DIR = "/opt/superset";
/** Mount target for the per-workspace isolated git dir. */
export const CONTAINER_GIT_DIR = "/sandbox/git";
/** Mount target for the per-workspace host-access dir (CLI token). */
export const CONTAINER_HOST_DIR = "/sandbox/host";
/**
 * Home of the default sandbox image's user (root). Agent-config mounts
 * target it; custom images with a different default user should disable
 * `sandbox.agentConfig` until per-image homes are configurable.
 */
export const CONTAINER_HOME_DIR = "/root";
/** In-container SUPERSET_HOME_DIR contents live under CONTAINER_SUPERSET_DIR. */
export const CONTAINER_BASH_RCFILE = `${CONTAINER_SUPERSET_DIR}/bash/rcfile`;

export function getSupersetHomeDir(): string {
	return process.env.SUPERSET_HOME_DIR || join(homedir(), ".superset");
}

/** Root for all host-side sandbox state. */
export function getSandboxRootDir(): string {
	return join(getSupersetHomeDir(), "sandbox");
}

/**
 * Host-side directory generated by sandbox-home.ts and bind-mounted
 * read-only at CONTAINER_SUPERSET_DIR in every sandbox container.
 */
export function getSandboxHomeDir(): string {
	return join(getSandboxRootDir(), "home");
}

export interface WorkspaceSandboxPaths {
	/** Per-workspace state root; removed on workspace delete. */
	stateDir: string;
	/** Isolated git dir bind-mounted at CONTAINER_GIT_DIR. */
	gitDir: string;
	/** One-line mask bind-mounted read-only over <worktree>/.git. */
	dotGitFile: string;
	/** HEAD sha the sandbox git dir was bootstrapped from. */
	bootstrapShaFile: string;
	/**
	 * Host dir for staged launch scripts (long initial commands / fish prompt
	 * transport), bind-mounted at the SAME path inside the container so the
	 * `source <path>` the shell runs resolves in both. Removed with stateDir.
	 */
	launchDir: string;
}

export function getWorkspaceSandboxPaths(
	workspaceId: string,
): WorkspaceSandboxPaths {
	const stateDir = join(getSandboxRootDir(), "workspaces", workspaceId);
	return {
		stateDir,
		gitDir: join(stateDir, "git"),
		dotGitFile: join(stateDir, "dot-git"),
		bootstrapShaFile: join(stateDir, "bootstrap-sha"),
		launchDir: join(stateDir, "launch"),
	};
}

const CONTAINER_SLUG_MAX = 30;

/**
 * Docker-safe, human-readable slug from workspace naming parts (name,
 * branch). Duplicate/empty parts collapse; "" when nothing usable survives.
 */
export function sandboxNameSlug(
	...parts: Array<string | null | undefined>
): string {
	const unique = [...new Set(parts.filter((p): p is string => !!p))];
	return unique
		.join("-")
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^-+|-+$/g, "")
		.slice(0, CONTAINER_SLUG_MAX)
		.replace(/-+$/, "");
}

/**
 * Container name: readable slug (so Docker Desktop shows which workspace it
 * is) + short workspace-id suffix for uniqueness. The workspace-id LABEL is
 * authoritative for cleanup — names are display + exec targeting only.
 */
export function getSandboxContainerName(
	workspaceId: string,
	nameSlug?: string,
): string {
	if (!nameSlug) return `superset-ws-${workspaceId}`;
	return `superset-${nameSlug}-${workspaceId.slice(0, 8)}`;
}
