export {
	LEGACY_VOICE_INPUT_SETTINGS_SECTION_ID,
	LEGACY_VOICE_SHORTCUT_SECTION_ID,
	VOICE_CONTROL_SECTION_ID,
	VOICE_INPUT_HOTKEY_ID,
	VOICE_INPUT_SETTINGS_HREF,
	VOICE_INPUT_SETTINGS_SECTION_ID,
	VOICE_SHORTCUT_SECTION_ID,
	VOICE_SHORTCUT_SETTINGS_HREF,
} from "./voice-shortcut-links";
