// scripts/patch-node-pty-win.ts
// Patches node-pty's gyp files for Windows builds:
// 1. Removes Spectre mitigation requirement (not installed by default)
// 2. Hardcodes winpty commit hash (bat file execution fails in gyp context)
// 3. Pre-creates GenVersion.h header

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

if (process.platform !== "win32") {
	process.exit(0);
}

const nodePtyBase = join(
	import.meta.dir,
	"..",
	"node_modules",
	".bun",
	"node-pty@1.1.0",
	"node_modules",
	"node-pty",
);

if (!existsSync(nodePtyBase)) {
	console.log("node-pty not found, skipping patch");
	process.exit(0);
}

// Patch binding.gyp - remove Spectre mitigation
const bindingGyp = join(nodePtyBase, "binding.gyp");
if (existsSync(bindingGyp)) {
	let content = readFileSync(bindingGyp, "utf-8");
	content = content.replace(
		"'SpectreMitigation': 'Spectre'",
		"",
	);
	writeFileSync(bindingGyp, content);
	console.log("Patched binding.gyp: removed Spectre mitigation");
}

// Patch winpty.gyp - remove Spectre + fix bat file execution
const winptyGyp = join(nodePtyBase, "deps", "winpty", "src", "winpty.gyp");
if (existsSync(winptyGyp)) {
	let content = readFileSync(winptyGyp, "utf-8");
	// Remove Spectre mitigation
	content = content.replaceAll("'SpectreMitigation': 'Spectre'", "");
	// Replace GetCommitHash.bat call with hardcoded value
	content = content.replace(
		/'\<!\(cmd \/c "cd shared && .*?GetCommitHash\.bat"\)'/,
		"'none'",
	);
	// Replace UpdateGenVersion.bat call with hardcoded include dir
	content = content.replace(
		/'\<!\(cmd \/c "cd shared && .*?UpdateGenVersion\.bat.*?"\)'/,
		"'gen'",
	);
	writeFileSync(winptyGyp, content);
	console.log("Patched winpty.gyp: removed Spectre, hardcoded version values");
}

// Pre-create GenVersion.h
const versionFile = join(nodePtyBase, "deps", "winpty", "VERSION.txt");
const version = existsSync(versionFile)
	? readFileSync(versionFile, "utf-8").trim()
	: "0.4.4-dev";

const genDir = join(nodePtyBase, "deps", "winpty", "src", "gen");
mkdirSync(genDir, { recursive: true });
writeFileSync(
	join(genDir, "GenVersion.h"),
	`// AUTO-GENERATED by patch-node-pty-win.ts\nconst char GenVersion_Version[] = "${version}";\nconst char GenVersion_Commit[] = "none";\n`,
);
console.log("Created gen/GenVersion.h");
